### ISSUE TITLE
Coin passed in as baseline gets characters after the first changed to lowercase

### ISSUE THREAD

**Issue by Torpus** [Torpus/CoinPicker#3]
In the scenario where a coin like LBRY is passed in the code changes it to Lbry but the response json is keyed for LBRY.  Nice feature for being able to pass in 'ethereum' and have it changed to 'Ethereum' but breaks for coins being returned from the rest call in all caps.  Will look into a fix.
```
python3 coinPicker.py -c LBRY -f approvedCoinFile
Traceback (most recent call last):
  File "coinPicker.py", line 48, in <module>
    fetchCoinJson(coin,coinFile)
  File "coinPicker.py", line 36, in fetchCoinJson
    print(coin + ' = ' + str(rJson[coin]['profitability']) + ' :: ' + coinToMine + ' = ' + str(rJson[coinToMine]['profitability']))
KeyError: 'Lbry'
```

**Comment by Torpus** [comment]
fixed
